---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: scottenriquez-karpenter-demo
  region: us-west-2
  version: "1.28"
  tags:
    karpenter.sh/discovery: scottenriquez-karpenter-demo

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: karpenter
      namespace: "karpenter"
    roleName: scottenriquez-karpenter-demo-karpenter
    attachPolicyARNs:
    - arn:aws:iam::196736724465:policy/KarpenterControllerPolicy-scottenriquez-karpenter-demo
    roleOnly: true

iamIdentityMappings:
- arn: "arn:aws:iam::196736724465:role/KarpenterNodeRole-scottenriquez-karpenter-demo"
  username: system:node:{{EC2PrivateDNSName}}
  groups:
  - system:bootstrappers
  - system:nodes

managedNodeGroups:
- instanceType: t3.medium
  amiFamily: AmazonLinux2
  name: scottenriquez-karpenter-demo-ng
  desiredCapacity: 2
  minSize: 2
  maxSize: 5
