kind: Service
apiVersion: v1
metadata:
  name: blue-test-service
  labels:
    env: blue
spec:
  type: ClusterIP
  selector:
    app: nginx
    role: blue
  ports:
    - port: 9000
      targetPort: 80